# [dbo].[Ders]

In [0]:
USE [OkulYonetim]
GO

In [0]:
/****** Object:  Table [dbo].[Ders]    Script Date: 17.01.2023 21:01:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ders](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[Ad] [varchar](30) NULL,
	[Kredisi] [float] NULL,
	[OkulYonetimId] [int] NULL,
	[DersRenk] [int] NULL,
 CONSTRAINT [PK_Ders] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Ogrenci]

In [0]:
/****** Object:  Table [dbo].[Ogrenci]    Script Date: 17.01.2023 21:01:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Ogrenci](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[AdSoyad] [varchar](30) NULL,
	[KayitTarih] [datetime2](7) NULL,
	[OgrenciNo] [varchar](11) NULL,
	[DTarih] [date] NULL,
	[Bolum] [varchar](30) NULL,
 CONSTRAINT [PK_Ogrenci] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[OgrenciDers]

In [0]:
/****** Object:  Table [dbo].[OgrenciDers]    Script Date: 17.01.2023 21:01:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[OgrenciDers](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[DersId] [int] NULL,
	[OgrenciId] [int] NULL,
 CONSTRAINT [PK_OgrenciDers] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Personel]

In [0]:
/****** Object:  Table [dbo].[Personel]    Script Date: 17.01.2023 21:01:27 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[Personel](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[AdSoyad] [varchar](30) NULL,
	[Gorevi] [varchar](50) NULL,
	[YonetimTip] [int] NULL,
 CONSTRAINT [PK_OkulYonetim] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO

# [dbo].[Ders]

In [0]:
SET IDENTITY_INSERT [dbo].[Ders] ON 
INSERT [dbo].[Ders] ([Id], [Ad], [Kredisi], [OkulYonetimId], [DersRenk]) VALUES (1, N'Programlama Temelleri', 5.5, 4, 1)
INSERT [dbo].[Ders] ([Id], [Ad], [Kredisi], [OkulYonetimId], [DersRenk]) VALUES (2, N'Jedi Eğitimine Giriş', 7.5, 3, 2)
INSERT [dbo].[Ders] ([Id], [Ad], [Kredisi], [OkulYonetimId], [DersRenk]) VALUES (3, N'Tarih', 2, 1, 3)
INSERT [dbo].[Ders] ([Id], [Ad], [Kredisi], [OkulYonetimId], [DersRenk]) VALUES (4, N'Roma Hukuku', 6, 2, 4)
INSERT [dbo].[Ders] ([Id], [Ad], [Kredisi], [OkulYonetimId], [DersRenk]) VALUES (5, N'Python Giriş', 3, 4, 5)
INSERT [dbo].[Ders] ([Id], [Ad], [Kredisi], [OkulYonetimId], [DersRenk]) VALUES (6, N'Form III Tekniğine Giriş', 12.5, 3, 6)
INSERT [dbo].[Ders] ([Id], [Ad], [Kredisi], [OkulYonetimId], [DersRenk]) VALUES (7, N'Genel Veritabanı Tasarımı', 4, 4, 7)
INSERT [dbo].[Ders] ([Id], [Ad], [Kredisi], [OkulYonetimId], [DersRenk]) VALUES (9, N'Girişimcilik', 6, 4, 10)
SET IDENTITY_INSERT [dbo].[Ders] OFF
GO

# [dbo].[Ogrenci]

In [0]:
SET IDENTITY_INSERT [dbo].[Ogrenci] ON 
INSERT [dbo].[Ogrenci] ([Id], [AdSoyad], [KayitTarih], [OgrenciNo], [DTarih], [Bolum]) VALUES (5, N'Sadettin Durmasın', CAST(N'2022-12-07T06:10:37.0000000' AS DateTime2), N'20200108033', CAST(N'2001-07-01' AS Date), N'Eczacılık')
INSERT [dbo].[Ogrenci] ([Id], [AdSoyad], [KayitTarih], [OgrenciNo], [DTarih], [Bolum]) VALUES (6, N'Abuzer Kömürcü', CAST(N'2022-12-07T06:10:37.0000000' AS DateTime2), N'20200108024', CAST(N'1960-01-01' AS Date), N'Kimya')
INSERT [dbo].[Ogrenci] ([Id], [AdSoyad], [KayitTarih], [OgrenciNo], [DTarih], [Bolum]) VALUES (7, N'Anakin Skywalker', CAST(N'2022-12-07T06:10:37.0000000' AS DateTime2), N'20200108035', CAST(N'1981-04-19' AS Date), N'Jedi Eğitim Fakültesi')
SET IDENTITY_INSERT [dbo].[Ogrenci] OFF
GO

# [dbo].[OgrenciDers]

In [0]:
SET IDENTITY_INSERT [dbo].[OgrenciDers] ON 
INSERT [dbo].[OgrenciDers] ([Id], [DersId], [OgrenciId]) VALUES (2, 5, 5)
INSERT [dbo].[OgrenciDers] ([Id], [DersId], [OgrenciId]) VALUES (3, 3, 6)
INSERT [dbo].[OgrenciDers] ([Id], [DersId], [OgrenciId]) VALUES (5, 2, 7)
INSERT [dbo].[OgrenciDers] ([Id], [DersId], [OgrenciId]) VALUES (9, 4, 5)
INSERT [dbo].[OgrenciDers] ([Id], [DersId], [OgrenciId]) VALUES (10, 5, 5)
INSERT [dbo].[OgrenciDers] ([Id], [DersId], [OgrenciId]) VALUES (11, 2, 5)
INSERT [dbo].[OgrenciDers] ([Id], [DersId], [OgrenciId]) VALUES (12, 2, 7)
INSERT [dbo].[OgrenciDers] ([Id], [DersId], [OgrenciId]) VALUES (13, 5, 7)
SET IDENTITY_INSERT [dbo].[OgrenciDers] OFF
GO

# [dbo].[Personel]

In [0]:
SET IDENTITY_INSERT [dbo].[Personel] ON 
INSERT [dbo].[Personel] ([Id], [AdSoyad], [Gorevi], [YonetimTip]) VALUES (1, N'Sadettin Dursun', N'Ders Anlatmak', 12)
INSERT [dbo].[Personel] ([Id], [AdSoyad], [Gorevi], [YonetimTip]) VALUES (2, N'Recep Dursun', N'Yönetimden Sorumlu', 11)
INSERT [dbo].[Personel] ([Id], [AdSoyad], [Gorevi], [YonetimTip]) VALUES (3, N'Obi-Wan Kenobi', N'Jedi Eğitmeni', 12)
INSERT [dbo].[Personel] ([Id], [AdSoyad], [Gorevi], [YonetimTip]) VALUES (4, N'Refik Tanju Sirmen', N'Ders Anlatmak', 12)
INSERT [dbo].[Personel] ([Id], [AdSoyad], [Gorevi], [YonetimTip]) VALUES (5, N'Tony Stark', N'Demirden bir adam', 12)
SET IDENTITY_INSERT [dbo].[Personel] OFF
GO

# [FK_Ders_OkulYonetim]

In [0]:
ALTER TABLE [dbo].[Ders]  WITH CHECK ADD  CONSTRAINT [FK_Ders_OkulYonetim] FOREIGN KEY([OkulYonetimId])
REFERENCES [dbo].[Personel] ([Id])
GO
ALTER TABLE [dbo].[Ders] CHECK CONSTRAINT [FK_Ders_OkulYonetim]
GO

# [FK_OgrenciDers_Ders]

In [0]:
ALTER TABLE [dbo].[OgrenciDers]  WITH CHECK ADD  CONSTRAINT [FK_OgrenciDers_Ders] FOREIGN KEY([DersId])
REFERENCES [dbo].[Ders] ([Id])
GO
ALTER TABLE [dbo].[OgrenciDers] CHECK CONSTRAINT [FK_OgrenciDers_Ders]
GO

# [FK_OgrenciDers_Ogrenci]

In [0]:
ALTER TABLE [dbo].[OgrenciDers]  WITH CHECK ADD  CONSTRAINT [FK_OgrenciDers_Ogrenci] FOREIGN KEY([OgrenciId])
REFERENCES [dbo].[Ogrenci] ([Id])
GO
ALTER TABLE [dbo].[OgrenciDers] CHECK CONSTRAINT [FK_OgrenciDers_Ogrenci]
GO